server:
    port: 8080
    servlet:
        context-path: /
    error:
        include-message: always
        include-binding-errors: always
        include-stacktrace: on_param
        include-exception: false
spring:
    ##
    # DataSource and JPA/Hibernate (H2)
    ##
    datasource:
        driverClassName: org.h2.Driver
        url: jdbc:h2:mem:dev_db
        username: sa
        password: sa
        hikari:
            auto-commit: false
            maximum-pool-size: 20
            connection-timeout: 10000       # 10s
            validation-timeout: 5000        # 5s
            max-lifetime: 1800000           # 30min
            leak-detection-threshold: 60000 # 1min
    h2:
        console: # http://localhost:8080/h2-console/
            enabled: true
    jpa:
        generate-ddl: true
        show-sql: true
        open-in-view: false
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true
                jdbc:
                    time_zone: UTC
                    batch_size: 15
                    order_inserts: true
                    order_updates: true
                    batch_versioned_data: true
                connection:
                    provider_disables_autocommit: true
                query:
                    in_clause_parameter_padding: true
                    fail_on_pagination_over_collection_fetch: true
                    plan_cache_max_size: 4096
    application:
        name: demo
    output:
        ansi:
            enabled: ALWAYS
management:
    endpoints:
        jmx:
            exposure:
                include: '*'
        web:
            exposure:
                include: health,metrics,env
    endpoint:
        health:
            show-details: always
            show-components: always
            probes:
                enabled: true
                add-additional-paths: true
